- basename_vm: db-asm-
  num_vm: 1
  hostgroup: vbox-si-asm
  domain: internal.lab
  box: oravirt/ol73
  vagrant_user: vagrant
  vagrant_pass: vagrant
  #vagrant_private_key: /vagrant/base-provision/insecure_private_key
  ram: 4096
  cpu: 1
  base_pub_ip: 192.168.9.62
  synced_folders:
     - {src: swrepo, dest: /media/swrepo}
     #- {src: /Users/miksan/Downloads/oracle, dest: /media/swrepo}
  base_disk_path:
  create_local_disk: true
  local_disks:
     - {name: u01, size: 75, count: 1}
     - {name: crs, size: 10, count: 1}
     - {name: data, size: 10, count: 2}
     - {name: fra, size: 10, count: 3}
  create_shared_disk: false
  provisioning: extra-provision/ansible-oracle/vbox-si-asm-install.yml
  provisioning_env_override: false
